// src/embed.rs

/// The raw bytes of the compressed Qt Engine.
/// This file is generated by build.rs scanning the /dist folder.
pub const PAYLOAD_ZIP: &[u8] = include_bytes!("embed/capture_engine.zip");

/// Critical for the "Matryoshka" extraction logic.
/// If you update the Qt engine, BUMP THIS VERSION.
/// This forces the client to delete the old AppData folder and re-extract.
include!("embed/version_hash.rs");