name: "Build Daemon"
description: "Builds Rust Daemon for specific OS"
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # --- BUILD ---
    - name: Build
      working-directory: ./packages/capture
      shell: bash
      run: |
        cargo update
        cargo build --release

    # --- ZIP OUTPUT ---
    - name: Zip Artifacts
      shell: bash
      run: |
        mkdir -p dist-out

        # Determine OS Tag
        if [ "$RUNNER_OS" == "Windows" ]; then
          OS_TAG="win"
          BIN_NAME="spatialshot-daemon.exe"
        elif [ "$RUNNER_OS" == "Linux" ]; then
          OS_TAG="linux"
          BIN_NAME="spatialshot-daemon"
        elif [ "$RUNNER_OS" == "macOS" ]; then
          OS_TAG="mac"
          BIN_NAME="spatialshot-daemon"
        fi

        # Determine Arch
        MACHINE_ARCH=$(uname -m)
        if [[ "$MACHINE_ARCH" == 'arm64' ]]; then
           ARCH="arm64"
        else
           ARCH="x64"
        fi

        ZIP_NAME="spatialshot-daemon-${OS_TAG}-${ARCH}.zip"

        # Correct path to artifact
        BIN_PATH="packages/capture/target/release/$BIN_NAME"

        if [ ! -f "$BIN_PATH" ]; then
            echo "::error::Binary not found at $BIN_PATH"
            ls -R packages/capture/target
            exit 1
        fi

        echo "Zipping $BIN_PATH to $ZIP_NAME..."

        if [ "$RUNNER_OS" == "Windows" ]; then
          7z a -tzip "dist-out/$ZIP_NAME" "./$BIN_PATH"
        else
          zip -j "dist-out/$ZIP_NAME" "$BIN_PATH"
        fi